import { db } from '@/lib/watchlists/db';
import { requireOrganizationAccess } from '@/lib/operations/authorization';
import type { OrganizationActor } from '@/lib/operations/types';
import type { CyberAssetInput, CyberClientInput, InventoryVerificationState, VendorDependencyInput } from './types';
import { validateCyberAssetInput, validateCyberClientInput, validateVendorDependencyInput } from './validation';

export interface CyberClient extends CyberClientInput { id: string; organizationId: string; status: 'active' | 'archived'; createdAt: string; updatedAt: string; }
export interface CyberAsset extends CyberAssetInput { id: string; organizationId: string; archivedAt?: string; inventoryState: InventoryVerificationState; createdAt: string; updatedAt: string; }
export interface VendorDependency extends VendorDependencyInput { id: string; organizationId: string; archivedAt?: string; createdAt: string; updatedAt: string; }

interface ClientRow { id: string; organization_id: string; name: string; reference: string; timezone: string | null; account_owner_user_id: string | null; technical_owner_user_id: string | null; security_contact: string | null; executive_contact: string | null; escalation_contact: string | null; service_tier: string | null; response_sla_hours: number | null; remediation_sla_hours: number | null; tags: string[]; status: 'active' | 'archived'; created_at: string; updated_at: string; }
interface AssetRow { id: string; organization_id: string; customer_id: string; asset_name: string; asset_type: string; hostname: string | null; domain: string | null; ip_address: string | null; exposure_scope: CyberAssetInput['exposureScope']; internet_facing: boolean | null; vendor: string | null; product: string | null; product_version: string | null; operating_system: string | null; software_package: string | null; cloud_provider: string | null; cloud_account: string | null; cloud_region: string | null; environment: string; criticality: number; asset_owner: string | null; technical_owner: string | null; inventory_source: string | null; inventory_confidence: number | null; last_observed_at: string | null; last_verified_at: string | null; verification_status: InventoryVerificationState; archived_at: string | null; created_at: string; updated_at: string; }
interface DependencyRow { id: string; organization_id: string; customer_id: string; vendor: string; product_or_service: string | null; dependency_type: VendorDependencyInput['dependencyType']; business_criticality: number; internal_owner: string | null; security_contact: string | null; verification_status: InventoryVerificationState; last_verified_at: string | null; archived_at: string | null; created_at: string; updated_at: string; }

const client = (row: ClientRow): CyberClient => ({ id: row.id, organizationId: row.organization_id, name: row.name, reference: row.reference, timezone: row.timezone ?? 'UTC', accountOwnerUserId: row.account_owner_user_id ?? undefined, technicalOwnerUserId: row.technical_owner_user_id ?? undefined, securityContact: row.security_contact ?? undefined, executiveContact: row.executive_contact ?? undefined, escalationContact: row.escalation_contact ?? undefined, serviceTier: row.service_tier ?? undefined, responseSlaHours: row.response_sla_hours ?? undefined, remediationSlaHours: row.remediation_sla_hours ?? undefined, tags: row.tags ?? [], status: row.status, createdAt: row.created_at, updatedAt: row.updated_at });
function inventoryState(status: InventoryVerificationState, verifiedAt: string | null): InventoryVerificationState { return verifiedAt && Date.now() - Date.parse(verifiedAt) > 1000 * 60 * 60 * 24 * 30 ? 'inventory_stale' : status; }
const asset = (row: AssetRow): CyberAsset => ({ id: row.id, organizationId: row.organization_id, customerId: row.customer_id, assetName: row.asset_name, assetType: row.asset_type, hostname: row.hostname ?? undefined, domain: row.domain ?? undefined, ipAddress: row.ip_address ?? undefined, exposureScope: row.exposure_scope, internetFacing: row.internet_facing ?? undefined, vendor: row.vendor ?? undefined, product: row.product ?? undefined, productVersion: row.product_version ?? undefined, operatingSystem: row.operating_system ?? undefined, softwarePackage: row.software_package ?? undefined, cloudProvider: row.cloud_provider ?? undefined, cloudAccount: row.cloud_account ?? undefined, cloudRegion: row.cloud_region ?? undefined, environment: row.environment, criticality: row.criticality, technicalOwner: row.technical_owner ?? undefined, assetOwner: row.asset_owner ?? undefined, inventorySource: row.inventory_source ?? undefined, inventoryConfidence: row.inventory_confidence ?? undefined, lastObservedAt: row.last_observed_at ?? undefined, lastVerifiedAt: row.last_verified_at ?? undefined, verificationStatus: row.verification_status, inventoryState: inventoryState(row.verification_status, row.last_verified_at), archivedAt: row.archived_at ?? undefined, createdAt: row.created_at, updatedAt: row.updated_at });
const dependency = (row: DependencyRow): VendorDependency => ({ id: row.id, organizationId: row.organization_id, customerId: row.customer_id, vendor: row.vendor, productOrService: row.product_or_service ?? undefined, dependencyType: row.dependency_type, businessCriticality: row.business_criticality, internalOwner: row.internal_owner ?? undefined, securityContact: row.security_contact ?? undefined, verificationStatus: row.verification_status, lastVerifiedAt: row.last_verified_at ?? undefined, archivedAt: row.archived_at ?? undefined, createdAt: row.created_at, updatedAt: row.updated_at });

async function requireClient(actor: OrganizationActor, clientId: string): Promise<void> { const result = await db().query('select 1 from ophanim_customers where id = $1 and organization_id = $2 and status = \'active\'', [clientId, actor.organizationId]); if (!result.rowCount) throw new Error('Client was not found in this organization.'); }
async function requireMember(actor: OrganizationActor, userId?: string): Promise<void> { if (!userId) return; const result = await db().query('select 1 from ophanim_organization_memberships where organization_id = $1 and user_id = $2', [actor.organizationId, userId]); if (!result.rowCount) throw new Error('The selected client owner does not belong to this organization.'); }

export async function listCyberClients(actor: OrganizationActor): Promise<CyberClient[]> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:read'); return (await db().query<ClientRow>('select id,organization_id,name,reference,timezone,account_owner_user_id,technical_owner_user_id,security_contact,executive_contact,escalation_contact,service_tier,response_sla_hours,remediation_sla_hours,tags,status,created_at,updated_at from ophanim_customers where organization_id=$1 and status=\'active\' order by name', [actor.organizationId])).rows.map(client); }
export async function createCyberClient(actor: OrganizationActor, input: unknown): Promise<CyberClient> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:write'); const value = validateCyberClientInput(input); await requireMember(actor, value.accountOwnerUserId); await requireMember(actor, value.technicalOwnerUserId); const result = await db().query<ClientRow>('insert into ophanim_customers(organization_id,name,reference,timezone,account_owner_user_id,technical_owner_user_id,security_contact,executive_contact,escalation_contact,service_tier,response_sla_hours,remediation_sla_hours,tags) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning id,organization_id,name,reference,timezone,account_owner_user_id,technical_owner_user_id,security_contact,executive_contact,escalation_contact,service_tier,response_sla_hours,remediation_sla_hours,tags,status,created_at,updated_at', [actor.organizationId,value.name,value.reference,value.timezone ?? 'UTC',value.accountOwnerUserId ?? null,value.technicalOwnerUserId ?? null,value.securityContact ?? null,value.executiveContact ?? null,value.escalationContact ?? null,value.serviceTier ?? null,value.responseSlaHours ?? null,value.remediationSlaHours ?? null,JSON.stringify(value.tags ?? [])]); await db().query('insert into ophanim_audit_events(organization_id,actor_user_id,action,subject_type,subject_id,metadata) values($1,$2,\'cyber.client_created\',\'cyber_client\',$3,$4)', [actor.organizationId,actor.userId,result.rows[0].id,JSON.stringify({ reference:value.reference })]); return client(result.rows[0]); }

export async function listCyberAssets(actor: OrganizationActor, customerId?: string): Promise<CyberAsset[]> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:read'); const result = await db().query<AssetRow>(`select id,organization_id,customer_id,asset_name,asset_type,hostname,domain,host(ip_address) as ip_address,exposure_scope,internet_facing,vendor,product,product_version,operating_system,software_package,cloud_provider,cloud_account,cloud_region,environment,criticality,asset_owner,technical_owner,inventory_source,inventory_confidence,last_observed_at,last_verified_at,verification_status,archived_at,created_at,updated_at from ophanim_assets where organization_id=$1 and archived_at is null${customerId ? ' and customer_id=$2' : ''} order by criticality desc,asset_name`, customerId ? [actor.organizationId, customerId] : [actor.organizationId]); return result.rows.map(asset); }
export async function createCyberAsset(actor: OrganizationActor, input: unknown): Promise<CyberAsset> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:write'); const value = validateCyberAssetInput(input); await requireClient(actor, value.customerId); const result = await db().query<AssetRow>('insert into ophanim_assets(organization_id,customer_id,asset_name,asset_type,hostname,domain,ip_address,exposure_scope,internet_facing,vendor,product,product_version,operating_system,software_package,cloud_provider,cloud_account,cloud_region,environment,criticality,asset_owner,technical_owner,inventory_source,inventory_confidence,last_observed_at,last_verified_at,verification_status,owner_user_id,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7::inet,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$27) returning id,organization_id,customer_id,asset_name,asset_type,hostname,domain,host(ip_address) as ip_address,exposure_scope,internet_facing,vendor,product,product_version,operating_system,software_package,cloud_provider,cloud_account,cloud_region,environment,criticality,asset_owner,technical_owner,inventory_source,inventory_confidence,last_observed_at,last_verified_at,verification_status,archived_at,created_at,updated_at', [actor.organizationId,value.customerId,value.assetName,value.assetType ?? 'other',value.hostname ?? null,value.domain ?? null,value.ipAddress ?? null,value.exposureScope ?? 'unknown',value.internetFacing ?? null,value.vendor ?? null,value.product ?? null,value.productVersion ?? null,value.operatingSystem ?? null,value.softwarePackage ?? null,value.cloudProvider ?? null,value.cloudAccount ?? null,value.cloudRegion ?? null,value.environment ?? 'unknown',value.criticality ?? 3,value.assetOwner ?? null,value.technicalOwner ?? null,value.inventorySource ?? null,value.inventoryConfidence ?? null,value.lastObservedAt ?? null,value.lastVerifiedAt ?? null,value.verificationStatus ?? 'verification_required',actor.userId]); await db().query('insert into ophanim_audit_events(organization_id,actor_user_id,action,subject_type,subject_id,metadata) values($1,$2,\'cyber.asset_created\',\'cyber_asset\',$3,$4)', [actor.organizationId,actor.userId,result.rows[0].id,JSON.stringify({ customerId:value.customerId, assetName:value.assetName })]); return asset(result.rows[0]); }

export async function listVendorDependencies(actor: OrganizationActor, customerId?: string): Promise<VendorDependency[]> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:read'); const result = await db().query<DependencyRow>(`select id,organization_id,customer_id,vendor,product_or_service,dependency_type,business_criticality,internal_owner,security_contact,verification_status,last_verified_at,archived_at,created_at,updated_at from ophanim_vendor_dependencies where organization_id=$1 and archived_at is null${customerId ? ' and customer_id=$2' : ''} order by business_criticality desc,vendor`, customerId ? [actor.organizationId,customerId] : [actor.organizationId]); return result.rows.map(dependency); }
export async function createVendorDependency(actor: OrganizationActor, input: unknown): Promise<VendorDependency> { requireOrganizationAccess(actor, actor.organizationId, 'cyber:write'); const value = validateVendorDependencyInput(input); await requireClient(actor, value.customerId); const result = await db().query<DependencyRow>('insert into ophanim_vendor_dependencies(organization_id,customer_id,vendor,product_or_service,dependency_type,business_criticality,internal_owner,security_contact,verification_status,last_verified_at,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id,organization_id,customer_id,vendor,product_or_service,dependency_type,business_criticality,internal_owner,security_contact,verification_status,last_verified_at,archived_at,created_at,updated_at', [actor.organizationId,value.customerId,value.vendor,value.productOrService ?? null,value.dependencyType ?? 'service',value.businessCriticality ?? 3,value.internalOwner ?? null,value.securityContact ?? null,value.verificationStatus ?? 'verification_required',value.lastVerifiedAt ?? null,actor.userId]); await db().query('insert into ophanim_audit_events(organization_id,actor_user_id,action,subject_type,subject_id,metadata) values($1,$2,\'cyber.vendor_dependency_created\',\'vendor_dependency\',$3,$4)', [actor.organizationId,actor.userId,result.rows[0].id,JSON.stringify({ customerId:value.customerId, vendor:value.vendor })]); return dependency(result.rows[0]); }
