import { isIP } from 'node:net';
import { INVENTORY_VERIFICATION_STATES, type CyberAssetInput, type CyberClientInput, type InventoryVerificationState, type VendorDependencyInput } from './types';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DOMAIN = /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i;

export class CyberValidationError extends Error { constructor(message: string) { super(message); this.name = 'CyberValidationError'; } }

function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new CyberValidationError(`${label} must be an object.`); return value as Record<string, unknown>; }
function text(value: unknown, field: string, max = 240): string | undefined { if (value === undefined || value === null || value === '') return undefined; if (typeof value !== 'string') throw new CyberValidationError(`${field} must be text.`); const result = value.trim().replace(/\s+/g, ' '); if (!result) return undefined; if (result.length > max) throw new CyberValidationError(`${field} must be ${max} characters or fewer.`); return result; }
function required(value: unknown, field: string, max = 240): string { const result = text(value, field, max); if (!result) throw new CyberValidationError(`${field} is required.`); return result; }
function uuid(value: unknown, field: string): string { const result = required(value, field, 64); if (!UUID.test(result)) throw new CyberValidationError(`${field} must be a UUID.`); return result; }
function integer(value: unknown, field: string, min: number, max: number): number | undefined { if (value === undefined || value === null || value === '') return undefined; const result = Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new CyberValidationError(`${field} must be an integer from ${min} to ${max}.`); return result; }
function timestamp(value: unknown, field: string): string | undefined { const result = text(value, field, 64); if (!result) return undefined; if (!Number.isFinite(Date.parse(result))) throw new CyberValidationError(`${field} must be a valid timestamp.`); return result; }
function verification(value: unknown): InventoryVerificationState | undefined { const result = text(value, 'Verification status', 64); if (!result) return undefined; if (!INVENTORY_VERIFICATION_STATES.includes(result as InventoryVerificationState)) throw new CyberValidationError('Verification status is invalid.'); return result as InventoryVerificationState; }
function tags(value: unknown): string[] | undefined { if (value === undefined || value === null || value === '') return undefined; const source = Array.isArray(value) ? value : typeof value === 'string' ? value.split(/[;,]/) : undefined; if (!source) throw new CyberValidationError('Tags must be a list.'); const result = [...new Set(source.map((item) => text(item, 'Tag', 64)?.toLowerCase()).filter((item): item is string => Boolean(item)))]; if (result.length > 30) throw new CyberValidationError('Tags must contain 30 values or fewer.'); return result; }

export function validateCyberClientInput(value: unknown): CyberClientInput {
  const input = object(value, 'Client input');
  return { name: required(input.name, 'Client name'), reference: required(input.reference, 'Client identifier', 160), timezone: text(input.timezone, 'Timezone', 64) ?? 'UTC', accountOwnerUserId: input.accountOwnerUserId === undefined ? undefined : uuid(input.accountOwnerUserId, 'Account owner user ID'), technicalOwnerUserId: input.technicalOwnerUserId === undefined ? undefined : uuid(input.technicalOwnerUserId, 'Technical owner user ID'), securityContact: text(input.securityContact, 'Security contact'), executiveContact: text(input.executiveContact, 'Executive contact'), escalationContact: text(input.escalationContact, 'Escalation contact'), serviceTier: text(input.serviceTier, 'Service tier', 120), responseSlaHours: integer(input.responseSlaHours, 'Response SLA', 1, 8760), remediationSlaHours: integer(input.remediationSlaHours, 'Remediation SLA', 1, 8760), tags: tags(input.tags) };
}

export function validateCyberAssetInput(value: unknown): CyberAssetInput {
  const input = object(value, 'Asset input');
  const domain = text(input.domain, 'Domain', 253)?.toLowerCase(); if (domain && !DOMAIN.test(domain)) throw new CyberValidationError('Domain is invalid.');
  const ipAddress = text(input.ipAddress, 'IP address', 64); if (ipAddress && !isIP(ipAddress)) throw new CyberValidationError('IP address is invalid.');
  const exposureScope = text(input.exposureScope, 'Exposure scope', 32); if (exposureScope && !['public', 'internal', 'unknown'].includes(exposureScope)) throw new CyberValidationError('Exposure scope is invalid.');
  const internetFacing = input.internetFacing === undefined || input.internetFacing === '' ? undefined : input.internetFacing === true || input.internetFacing === 'true' || input.internetFacing === 'yes' ? true : input.internetFacing === false || input.internetFacing === 'false' || input.internetFacing === 'no' ? false : undefined;
  if (internetFacing === undefined && input.internetFacing !== undefined && input.internetFacing !== '') throw new CyberValidationError('Internet-facing status must be true or false.');
  return { customerId: uuid(input.customerId, 'Client ID'), assetName: required(input.assetName, 'Asset name'), assetType: text(input.assetType, 'Asset type', 120) ?? 'other', hostname: text(input.hostname, 'Hostname', 253)?.toLowerCase(), domain, ipAddress, exposureScope: exposureScope as CyberAssetInput['exposureScope'] ?? 'unknown', internetFacing, vendor: text(input.vendor, 'Vendor'), product: text(input.product, 'Product'), productVersion: text(input.productVersion, 'Product version'), operatingSystem: text(input.operatingSystem, 'Operating system'), softwarePackage: text(input.softwarePackage, 'Software package'), cloudProvider: text(input.cloudProvider, 'Cloud provider'), cloudAccount: text(input.cloudAccount, 'Cloud account'), cloudRegion: text(input.cloudRegion, 'Cloud region'), environment: text(input.environment, 'Environment', 120) ?? 'unknown', criticality: integer(input.criticality, 'Criticality', 1, 5) ?? 3, technicalOwner: text(input.technicalOwner, 'Technical owner'), assetOwner: text(input.assetOwner, 'Asset owner'), inventorySource: text(input.inventorySource, 'Inventory source'), inventoryConfidence: integer(input.inventoryConfidence, 'Inventory confidence', 0, 100), lastObservedAt: timestamp(input.lastObservedAt, 'Last observed time'), lastVerifiedAt: timestamp(input.lastVerifiedAt, 'Last verified time'), verificationStatus: verification(input.verificationStatus) ?? 'verification_required' };
}

export function validateVendorDependencyInput(value: unknown): VendorDependencyInput {
  const input = object(value, 'Vendor dependency input');
  const dependencyType = text(input.dependencyType, 'Dependency type', 32); if (dependencyType && !['service', 'software', 'cloud', 'supplier', 'integration', 'other'].includes(dependencyType)) throw new CyberValidationError('Dependency type is invalid.');
  return { customerId: uuid(input.customerId, 'Client ID'), vendor: required(input.vendor, 'Vendor'), productOrService: text(input.productOrService, 'Product or service'), dependencyType: dependencyType as VendorDependencyInput['dependencyType'] ?? 'service', businessCriticality: integer(input.businessCriticality, 'Business criticality', 1, 5) ?? 3, internalOwner: text(input.internalOwner, 'Internal owner'), securityContact: text(input.securityContact, 'Security contact'), verificationStatus: verification(input.verificationStatus) ?? 'verification_required', lastVerifiedAt: timestamp(input.lastVerifiedAt, 'Last verified time') };
}
