const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CVE = /^CVE-\d{4}-\d{4,}$/i;
export const ASSET_TYPES = ['server', 'workstation', 'network', 'cloud', 'application', 'identity', 'other'] as const;
export const ROLL_CALL_STATUSES = ['open', 'triage', 'remediation', 'monitoring', 'closed'] as const;
export const ASSESSMENT_STATUSES = ['unknown', 'not_affected', 'affected', 'mitigated', 'remediated', 'accepted_risk'] as const;
export const ROLL_CALL_DECISIONS = ['approve', 'reject', 'accept_risk', 'note'] as const;
export class RollCallValidationError extends Error { constructor(message: string) { super(message); this.name = 'RollCallValidationError'; } }
const object = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new RollCallValidationError('Input must be an object.'); return value as Record<string, unknown>; };
const text = (value: unknown, field: string, required = false, max = 300): string | undefined => { if (value === undefined || value === null || value === '') { if (required) throw new RollCallValidationError(`${field} is required.`); return undefined; } if (typeof value !== 'string') throw new RollCallValidationError(`${field} must be text.`); const result = value.trim(); if (!result && required) throw new RollCallValidationError(`${field} is required.`); if (result.length > max) throw new RollCallValidationError(`${field} is too long.`); return result || undefined; };
const choose = <T extends readonly string[]>(value: unknown, field: string, values: T): T[number] => { const result = text(value, field, true, 64); if (!result || !values.includes(result)) throw new RollCallValidationError(`${field} is invalid.`); return result as T[number]; };
const id = (value: unknown, field: string): string => { const result = text(value, field, true, 36); if (!result || !UUID.test(result)) throw new RollCallValidationError(`${field} is invalid.`); return result; };
const time = (value: unknown, field: string): string | undefined => { const result = text(value, field, false, 64); if (result && !Number.isFinite(Date.parse(result))) throw new RollCallValidationError(`${field} is invalid.`); return result; };
const url = (value: unknown): string => { const result = text(value, 'Source URL', true, 2048)!; try { const parsed = new URL(result); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); } catch { throw new RollCallValidationError('Source URL must be an HTTP(S) URL.'); } return result; };
export function validateAsset(value: unknown) { const input = object(value); const assetType = choose(input.assetType, 'Asset type', ASSET_TYPES); const criticality = Number(input.criticality ?? 3); if (!Number.isInteger(criticality) || criticality < 1 || criticality > 5) throw new RollCallValidationError('Criticality must be 1 through 5.'); return { assetName: text(input.assetName, 'Asset name', true, 240)!, assetType, environment: choose(input.environment ?? 'production', 'Environment', ['production', 'staging', 'development', 'other'] as const), criticality, externalReference: text(input.externalReference, 'External reference', false, 240) }; }
export function validateRollCall(value: unknown) { const input = object(value); const cveId = text(input.cveId, 'CVE ID', true, 32)?.toUpperCase(); if (!cveId || !CVE.test(cveId)) throw new RollCallValidationError('CVE ID is invalid.'); const cvssValue = input.cvss === undefined || input.cvss === null || input.cvss === '' ? undefined : Number(input.cvss); if (cvssValue !== undefined && (!Number.isFinite(cvssValue) || cvssValue < 0 || cvssValue > 10)) throw new RollCallValidationError('CVSS must be 0 through 10.'); return { cveId, title: text(input.title, 'Title', true)!, description: text(input.description, 'Description', false, 8000), cvss: cvssValue, knownExploited: input.knownExploited === true, sourceName: text(input.sourceName, 'Source name', false, 160) ?? 'operator', sourceUrl: input.sourceUrl ? url(input.sourceUrl) : undefined, dueAt: time(input.dueAt, 'Due time') }; }
export function validateAssessment(value: unknown) { const input = object(value); return { assetId: id(input.assetId, 'Asset ID'), assessmentStatus: choose(input.assessmentStatus, 'Assessment status', ASSESSMENT_STATUSES), dueAt: time(input.dueAt, 'Due time'), notes: text(input.notes, 'Notes', false, 4000) }; }
export function validateDecision(value: unknown) { const input = object(value); return { assessmentId: input.assessmentId ? id(input.assessmentId, 'Assessment ID') : undefined, decision: choose(input.decision, 'Decision', ROLL_CALL_DECISIONS), rationale: text(input.rationale, 'Rationale', true, 4000)! }; }
export function validateEvidence(value: unknown) { const input = object(value); return { assessmentId: input.assessmentId ? id(input.assessmentId, 'Assessment ID') : undefined, evidenceType: choose(input.evidenceType, 'Evidence type', ['advisory', 'scan', 'patch_note', 'change_record', 'approval', 'other'] as const), title: text(input.title, 'Evidence title', true)!, sourceUrl: url(input.sourceUrl), description: text(input.description, 'Description', false, 4000) }; }
export function validateRollCallStatus(value: unknown) { return choose(value, 'Roll call status', ROLL_CALL_STATUSES); }
