import { db } from '@/lib/watchlists/db';
import { requireOrganizationAccess } from '@/lib/operations/authorization';
import type { OrganizationActor } from '@/lib/operations/types';
import { ASSESSMENT_STATUSES, ROLL_CALL_STATUSES, validateAsset, validateAssessment, validateDecision, validateEvidence, validateRollCall, validateRollCallStatus } from './roll-call-validation';

type RollCallStatus = (typeof ROLL_CALL_STATUSES)[number]; type AssessmentStatus = (typeof ASSESSMENT_STATUSES)[number];
export interface Asset { id: string; assetName: string; assetType: string; environment: string; criticality: number; externalReference?: string; }
export interface Assessment { id: string; assetId: string; assetName: string; assessmentStatus: AssessmentStatus; dueAt?: string; notes?: string; assessedAt: string; }
export interface RollCallDecision { id: string; assessmentId?: string; decision: string; rationale: string; recordedAt: string; }
export interface RollCallEvidence { id: string; assessmentId?: string; evidenceType: string; title: string; sourceUrl: string; description?: string; capturedAt: string; }
export interface RollCall { id: string; cveId: string; title: string; description?: string; cvss?: number; knownExploited: boolean; sourceName: string; sourceUrl?: string; dueAt?: string; rollCallStatus: RollCallStatus; createdAt: string; updatedAt: string; assessments?: Assessment[]; decisions?: RollCallDecision[]; evidence?: RollCallEvidence[]; }
interface AssetRow { id: string; asset_name: string; asset_type: string; environment: string; criticality: number; external_reference: string | null; }
interface RollRow { id: string; cve_id: string; title: string; description: string | null; cvss: string | number | null; known_exploited: boolean; source_name: string; source_url: string | null; due_at: string | null; roll_call_status: RollCallStatus; created_at: string; updated_at: string; }
interface AssessmentRow { id: string; asset_id: string; asset_name: string; assessment_status: AssessmentStatus; due_at: string | null; notes: string | null; assessed_at: string; }
interface DecisionRow { id: string; asset_assessment_id: string | null; decision: string; rationale: string; recorded_at: string; }
interface EvidenceRow { id: string; asset_assessment_id: string | null; evidence_type: string; title: string; source_url: string; description: string | null; captured_at: string; }
const asset = (r: AssetRow): Asset => ({ id: r.id, assetName: r.asset_name, assetType: r.asset_type, environment: r.environment, criticality: r.criticality, externalReference: r.external_reference ?? undefined });
const roll = (r: RollRow): RollCall => ({ id: r.id, cveId: r.cve_id, title: r.title, description: r.description ?? undefined, cvss: r.cvss === null ? undefined : Number(r.cvss), knownExploited: r.known_exploited, sourceName: r.source_name, sourceUrl: r.source_url ?? undefined, dueAt: r.due_at ?? undefined, rollCallStatus: r.roll_call_status, createdAt: r.created_at, updatedAt: r.updated_at });
const assessment = (r: AssessmentRow): Assessment => ({ id: r.id, assetId: r.asset_id, assetName: r.asset_name, assessmentStatus: r.assessment_status, dueAt: r.due_at ?? undefined, notes: r.notes ?? undefined, assessedAt: r.assessed_at });
const decision = (r: DecisionRow): RollCallDecision => ({ id: r.id, assessmentId: r.asset_assessment_id ?? undefined, decision: r.decision, rationale: r.rationale, recordedAt: r.recorded_at });
const evidence = (r: EvidenceRow): RollCallEvidence => ({ id: r.id, assessmentId: r.asset_assessment_id ?? undefined, evidenceType: r.evidence_type, title: r.title, sourceUrl: r.source_url, description: r.description ?? undefined, capturedAt: r.captured_at });
async function hasRoll(actor: OrganizationActor, id: string) { return ((await db().query('select 1 from ophanim_zero_day_roll_calls where id=$1 and organization_id=$2', [id, actor.organizationId])).rowCount ?? 0) > 0; }
async function hasAssessment(actor: OrganizationActor, rollId: string, assessmentId: string) { return ((await db().query('select 1 from ophanim_zero_day_asset_assessments where id=$1 and roll_call_id=$2 and organization_id=$3', [assessmentId, rollId, actor.organizationId])).rowCount ?? 0) > 0; }
export async function listAssets(actor: OrganizationActor): Promise<Asset[]> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:read'); return (await db().query<AssetRow>('select id, asset_name, asset_type, environment, criticality, external_reference from ophanim_assets where organization_id=$1 order by criticality desc, asset_name', [actor.organizationId])).rows.map(asset); }
export async function createAsset(actor: OrganizationActor, input: unknown): Promise<Asset> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); const value = validateAsset(input); const r = await db().query<AssetRow>('insert into ophanim_assets (organization_id,asset_name,asset_type,environment,criticality,external_reference,owner_user_id,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$7) returning id,asset_name,asset_type,environment,criticality,external_reference', [actor.organizationId, value.assetName, value.assetType, value.environment, value.criticality, value.externalReference ?? null, actor.userId]); return asset(r.rows[0]); }
export async function listRollCalls(actor: OrganizationActor): Promise<RollCall[]> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:read'); return (await db().query<RollRow>('select id,cve_id,title,description,cvss,known_exploited,source_name,source_url,due_at,roll_call_status,created_at,updated_at from ophanim_zero_day_roll_calls where organization_id=$1 order by roll_call_status=\'closed\',due_at nulls last,updated_at desc', [actor.organizationId])).rows.map(roll); }
export async function getRollCall(actor: OrganizationActor, id: string): Promise<RollCall | null> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:read'); const base = await db().query<RollRow>('select id,cve_id,title,description,cvss,known_exploited,source_name,source_url,due_at,roll_call_status,created_at,updated_at from ophanim_zero_day_roll_calls where id=$1 and organization_id=$2', [id, actor.organizationId]); if (!base.rows[0]) return null; const [assessments, decisions, evidenceRows] = await Promise.all([db().query<AssessmentRow>('select a.id,a.asset_id,asset.asset_name,a.assessment_status,a.due_at,a.notes,a.assessed_at from ophanim_zero_day_asset_assessments a join ophanim_assets asset on asset.id=a.asset_id where a.roll_call_id=$1 and a.organization_id=$2 order by asset.asset_name', [id, actor.organizationId]), db().query<DecisionRow>('select id,asset_assessment_id,decision,rationale,recorded_at from ophanim_zero_day_decisions where roll_call_id=$1 and organization_id=$2 order by recorded_at desc', [id, actor.organizationId]), db().query<EvidenceRow>('select id,asset_assessment_id,evidence_type,title,source_url,description,captured_at from ophanim_zero_day_evidence where roll_call_id=$1 and organization_id=$2 order by captured_at desc', [id, actor.organizationId])]); return { ...roll(base.rows[0]), assessments: assessments.rows.map(assessment), decisions: decisions.rows.map(decision), evidence: evidenceRows.rows.map(evidence) }; }
export async function createRollCall(actor: OrganizationActor, input: unknown): Promise<RollCall> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); const value = validateRollCall(input); const r = await db().query<RollRow>('insert into ophanim_zero_day_roll_calls (organization_id,cve_id,title,description,cvss,known_exploited,source_name,source_url,due_at,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id,cve_id,title,description,cvss,known_exploited,source_name,source_url,due_at,roll_call_status,created_at,updated_at', [actor.organizationId,value.cveId,value.title,value.description ?? null,value.cvss ?? null,value.knownExploited,value.sourceName,value.sourceUrl ?? null,value.dueAt ?? null,actor.userId]); await db().query(`insert into ophanim_audit_events(organization_id,actor_user_id,action,subject_type,subject_id,metadata) values($1,$2,'roll_call.created','roll_call',$3,$4)`, [actor.organizationId,actor.userId,r.rows[0].id,JSON.stringify({ cveId:value.cveId })]); return roll(r.rows[0]); }
export async function updateRollCallStatus(actor: OrganizationActor, id: string, input: unknown): Promise<RollCall | null> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); const status = validateRollCallStatus((input as Record<string, unknown>)?.rollCallStatus); const r = await db().query('update ophanim_zero_day_roll_calls set roll_call_status=$3,updated_at=now() where id=$1 and organization_id=$2 returning id', [id, actor.organizationId, status]); if (!r.rowCount) return null; await db().query(`insert into ophanim_audit_events(organization_id,actor_user_id,action,subject_type,subject_id,metadata) values($1,$2,'roll_call.status_updated','roll_call',$3,$4)`, [actor.organizationId,actor.userId,id,JSON.stringify({ status })]); return getRollCall(actor,id); }
export async function upsertAssessment(actor: OrganizationActor, rollId: string, input: unknown): Promise<Assessment> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); if (!(await hasRoll(actor,rollId))) throw new Error('Roll call not found.'); const value = validateAssessment(input); const owned = await db().query('select 1 from ophanim_assets where id=$1 and organization_id=$2', [value.assetId,actor.organizationId]); if (!owned.rowCount) throw new Error('Asset not found.'); const r = await db().query<AssessmentRow>('insert into ophanim_zero_day_asset_assessments(organization_id,roll_call_id,asset_id,assessment_status,due_at,notes,owner_user_id,assessed_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$7) on conflict(organization_id,roll_call_id,asset_id) do update set assessment_status=excluded.assessment_status,due_at=excluded.due_at,notes=excluded.notes,assessed_by_user_id=excluded.assessed_by_user_id,assessed_at=now(),updated_at=now() returning id,asset_id,(select asset_name from ophanim_assets where id=asset_id) as asset_name,assessment_status,due_at,notes,assessed_at', [actor.organizationId,rollId,value.assetId,value.assessmentStatus,value.dueAt ?? null,value.notes ?? null,actor.userId]); return assessment(r.rows[0]); }
export async function addRollCallDecision(actor: OrganizationActor, rollId: string, input: unknown): Promise<RollCallDecision> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); if (!(await hasRoll(actor,rollId))) throw new Error('Roll call not found.'); const value = validateDecision(input); if (value.assessmentId && !(await hasAssessment(actor,rollId,value.assessmentId))) throw new Error('Assessment not found.'); const r = await db().query<DecisionRow>('insert into ophanim_zero_day_decisions(organization_id,roll_call_id,asset_assessment_id,decision,rationale,recorded_by_user_id) values($1,$2,$3,$4,$5,$6) returning id,asset_assessment_id,decision,rationale,recorded_at', [actor.organizationId,rollId,value.assessmentId ?? null,value.decision,value.rationale,actor.userId]); return decision(r.rows[0]); }
export async function addRollCallEvidence(actor: OrganizationActor, rollId: string, input: unknown): Promise<RollCallEvidence> { requireOrganizationAccess(actor, actor.organizationId, 'vulnerability:write'); if (!(await hasRoll(actor,rollId))) throw new Error('Roll call not found.'); const value = validateEvidence(input); if (value.assessmentId && !(await hasAssessment(actor,rollId,value.assessmentId))) throw new Error('Assessment not found.'); const r = await db().query<EvidenceRow>('insert into ophanim_zero_day_evidence(organization_id,roll_call_id,asset_assessment_id,evidence_type,title,source_url,description,captured_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,asset_assessment_id,evidence_type,title,source_url,description,captured_at', [actor.organizationId,rollId,value.assessmentId ?? null,value.evidenceType,value.title,value.sourceUrl,value.description ?? null,actor.userId]); return evidence(r.rows[0]); }
