import type { DarkWebProvider, DarkWebRawMention, DarkWebSearchQuery } from './types';

const now = '2026-08-03T00:00:00.000Z';
const fixtures: DarkWebRawMention[] = [
  { providerDocumentId: 'fixture-imo', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/imo', firstSeenAt: now, lastSeenAt: now, publishedAt: now, originalLanguage: 'en', originalText: 'IMO 9123456 discussed alongside AIS spoofing and replacement registry papers.', title: 'Exact vessel identifier', sourceReliability: 45, matchedIdentifiers: ['9123456'], threatCategories: ['ais_manipulation', 'forged_documents'] },
  { providerDocumentId: 'fixture-vessel-name', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/vessel-name', firstSeenAt: now, lastSeenAt: now, originalText: 'Example Star is mentioned near a terminal access claim.', title: 'Vessel name only', sourceReliability: 20, matchedIdentifiers: ['EXAMPLE STAR'], threatCategories: ['terminal_access'] },
  { providerDocumentId: 'fixture-mmsi', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/mmsi', firstSeenAt: now, lastSeenAt: now, originalText: 'MMSI 123456789 appears in an alleged identity laundering discussion.', title: 'Exact MMSI', sourceReliability: 40, matchedIdentifiers: ['123456789'], threatCategories: ['identity_laundering'] },
  { providerDocumentId: 'fixture-port', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/port', firstSeenAt: now, lastSeenAt: now, originalText: 'Terminal access credentials are claimed for Port Example, UNLOCODE EX PRT.', title: 'Port access claim', sourceReliability: 35, matchedIdentifiers: ['EXPRT'], threatCategories: ['terminal_access', 'credentials'] },
  { providerDocumentId: 'fixture-cable', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/cable', firstSeenAt: now, lastSeenAt: now, originalText: 'Northlink Cable landing station maintenance documents are discussed.', title: 'Cable landing station', sourceReliability: 30, matchedIdentifiers: ['NORTHLINK CABLE'], threatCategories: ['subsea_cable'] },
  { providerDocumentId: 'fixture-shadow-fleet', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/shadow-fleet', firstSeenAt: now, lastSeenAt: now, originalText: 'Shadow fleet sanctions evasion and ship-to-ship transfer terminology.', title: 'Generic maritime language', sourceReliability: 10, threatCategories: ['sanctions_evasion', 'ship_to_ship'] },
  { providerDocumentId: 'fixture-domain', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/domain', firstSeenAt: now, lastSeenAt: now, originalText: 'Credentials for example-client.com are claimed in a restricted post.', title: 'Exact client domain', sourceReliability: 45, matchedIdentifiers: ['example-client.com'], threatCategories: ['credential_exposure'] },
  { providerDocumentId: 'fixture-ransomware', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/ransomware', firstSeenAt: now, lastSeenAt: now, originalText: 'A ransomware leak claim names Example Client and an exposed VPN hostname.', title: 'Ransomware claim', sourceReliability: 35, matchedIdentifiers: ['EXAMPLE CLIENT'], threatCategories: ['ransomware', 'vpn_access'] },
  { providerDocumentId: 'fixture-access', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/access', firstSeenAt: now, lastSeenAt: now, originalText: 'Initial access listing includes 203.0.113.10 and an alleged administrative panel.', title: 'IP access claim', sourceReliability: 40, matchedIdentifiers: ['203.0.113.10'], threatCategories: ['initial_access'] },
  { providerDocumentId: 'fixture-false-positive', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/false-positive', firstSeenAt: now, lastSeenAt: now, originalText: 'Example Company is a generic phrase with no identifier or domain.', title: 'Weak company name', sourceReliability: 5, matchedIdentifiers: ['EXAMPLE COMPANY'], threatCategories: ['unverified_claim'] },
  { providerDocumentId: 'fixture-copy', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/copy', firstSeenAt: now, lastSeenAt: now, originalText: 'IMO 9123456 discussed alongside AIS spoofing and replacement registry papers.', title: 'Copied vessel identifier', sourceReliability: 20, matchedIdentifiers: ['9123456'], threatCategories: ['ais_manipulation', 'forged_documents'] },
  { providerDocumentId: 'fixture-independent', sourceCategory: 'development_fixture', sourceName: 'Ophanim development fixture', sourceReference: 'https://fixtures.invalid/independent', firstSeenAt: now, lastSeenAt: now, originalText: 'Independent source reports an AIS gap for IMO 9123456 with a separate source reference.', title: 'Independent corroboration', sourceReliability: 55, matchedIdentifiers: ['9123456'], threatCategories: ['ais_manipulation'] },
];

function enabled() { return process.env.NODE_ENV === 'test' || (process.env.NODE_ENV !== 'production' && process.env.DARK_WEB_FIXTURES_ENABLED === 'true'); }
function clean(value: string | undefined) { return value?.replace(/<[^>]*>/g, '').replace(/[\u0000-\u001f]/g, ' ').trim(); }

export const mockDarkWebProvider: DarkWebProvider = {
  metadata: { id: 'development-dark-web-fixtures', name: 'Development Dark-Web Fixtures', description: 'Safe, static test scenarios; never enabled in production.', sourceCategories: ['development_fixture'], supportedEntityTypes: ['vessel', 'port', 'terminal', 'subsea_cable', 'landing_station', 'company', 'carrier', 'client', 'asset', 'domain', 'ip', 'vendor', 'product', 'threat_actor'], authenticationRequirements: [], environmentVariables: ['DARK_WEB_FIXTURES_ENABLED'], rateLimitPerMinute: 60, timeoutMs: 1000, enabled: enabled(), commercialUse: 'allowed', retentionHours: 1, supportsHistoricalSearch: true, supportsContinuousMonitoring: false, supportsOriginalTimestamps: true, supportsSourceReferences: true, attachmentBehavior: 'none' },
  supports(query) { return query.entityTypes.length > 0; },
  async search(query, context) { if (!enabled()) return []; if (context.signal.aborted) throw new Error('Dark-web fixture query aborted.'); const words = query.query.toLowerCase().split(/\s+/).filter((word) => word.length > 2); return fixtures.filter((fixture) => words.length === 0 || words.some((word) => `${fixture.title} ${fixture.originalText} ${(fixture.matchedIdentifiers ?? []).join(' ')}`.toLowerCase().includes(word))).slice(0, Math.min(query.limit, 50)); },
  normalize(raw) { return { ...raw, title: clean(raw.title), originalText: clean(raw.originalText) ?? '', translatedText: clean(raw.translatedText), sourceReference: raw.sourceReference?.startsWith('https://') ? raw.sourceReference : undefined, matchedIdentifiers: raw.matchedIdentifiers?.map((identifier) => clean(identifier) ?? '').filter(Boolean), threatCategories: raw.threatCategories.map((category) => clean(category) ?? '').filter(Boolean) }; },
  async health() { return enabled() ? { status: 'healthy' as const } : { status: 'misconfigured' as const, detail: 'Development fixtures are disabled.' }; },
  validateConfiguration() { return enabled() ? { valid: true, errors: [] } : { valid: false, errors: ['Development fixtures require DARK_WEB_FIXTURES_ENABLED=true outside tests and are never available in production.'] }; },
  redact(raw) { return { ...raw, originalText: raw.originalText.slice(0, 20000), translatedText: raw.translatedText?.slice(0, 20000) }; },
};
