import { randomUUID } from 'crypto';
import { checkWatchlistProviders } from '@/lib/providers';
import { db } from './db';
import { entityLink, mapLink, watchlistLink } from '@/lib/links';

const valid = new Set(['ip','domain','ship','port','company','region','country','threat_actor']);
export type StoredWatchlist = { id:string; public_id:string; entity_type:string; entity_value:string; label:string|null; enabled:boolean; last_snapshot:unknown; next_check_at:string };
export async function listWatchlists(ownerId:string) { return (await db().query<StoredWatchlist>('select id,public_id,entity_type,entity_value,label,enabled,last_snapshot,next_check_at from ophanim_watchlists where owner_id=$1 order by created_at desc',[ownerId])).rows; }
export async function createWatchlist(ownerId:string, input:{type:string;value:string;label?:string}) { if(!valid.has(input.type)||!input.value.trim()) throw new Error('Invalid watchlist item.'); return (await db().query<StoredWatchlist>('insert into ophanim_watchlists(owner_id,entity_type,entity_value,label) values($1,$2,$3,$4) returning id,public_id,entity_type,entity_value,label,enabled,last_snapshot,next_check_at',[ownerId,input.type,input.value.trim(),input.label?.trim()||null])).rows[0]; }
export async function removeWatchlist(ownerId:string,id:string) { await db().query('delete from ophanim_watchlists where id=$1 and owner_id=$2',[id,ownerId]); }
export async function subscribe(ownerId:string,id:string,input:{email:string;mode:'immediate'|'digest';digestMinutes?:30|60}) { const email=input.email.trim().toLowerCase(); if(!/^\S+@\S+\.\S+$/.test(email)) throw new Error('Enter a valid email address.'); const result=await db().query('insert into ophanim_email_subscriptions(watchlist_id,email,mode,digest_minutes,next_digest_at) select id,$3,$4,$5,now()+($5||\' minutes\')::interval from ophanim_watchlists where id=$1 and owner_id=$2 returning verification_token',[id,ownerId,email,input.mode,input.digestMinutes||30]); if(!result.rowCount) throw new Error('Watchlist not found.'); return result.rows[0].verification_token as string; }
const fingerprint=(value:unknown)=>JSON.stringify(value, Object.keys(value as object).sort());
export async function checkDueWatchlists() { const rows=(await db().query<StoredWatchlist>('select * from ophanim_watchlists where enabled and next_check_at<=now() for update skip locked')).rows; for(const row of rows) { const response=await checkWatchlistProviders({type:row.entity_type as any,value:row.entity_value}); const snapshot={results:response.results,diagnostics:response.diagnostics}; const changed=!!row.last_snapshot && fingerprint(row.last_snapshot)!==fingerprint(snapshot); await db().query('update ophanim_watchlists set last_snapshot=$2,next_check_at=now()+interval \'5 minutes\',updated_at=now() where id=$1',[row.id,JSON.stringify(snapshot)]); if(changed) await queueChanges(row,snapshot); } return rows.length; }
async function queueChanges(row:StoredWatchlist,snapshot:any) { const subscriptions=(await db().query('select * from ophanim_email_subscriptions where watchlist_id=$1 and enabled and verified_at is not null',[row.id])).rows; for(const sub of subscriptions) { if(sub.mode==='digest') { await db().query('insert into ophanim_notifications(watchlist_id,subscription_id,kind,payload,next_attempt_at) values($1,$2,$3,$4,$5)',[row.id,sub.id,'digest',JSON.stringify(snapshot),sub.next_digest_at||new Date()]); } else { await db().query('insert into ophanim_notifications(watchlist_id,subscription_id,kind,payload) values($1,$2,$3,$4)',[row.id,sub.id,'immediate',JSON.stringify(snapshot)]); } } }
export async function verifySubscription(token:string) { await db().query('update ophanim_email_subscriptions set verified_at=now(),verification_token=null where verification_token=$1',[token]); }
export async function publicWatchlist(publicId:string) { return (await db().query<StoredWatchlist>('select id,public_id,entity_type,entity_value,label,enabled,last_snapshot,next_check_at from ophanim_watchlists where public_id=$1',[publicId])).rows[0]||null; }
export function notificationLinks(row:StoredWatchlist,snapshot:any) { const first=snapshot.results?.find((r:any)=>typeof r.lat==='number'&&typeof r.lng==='number'); return { watchlist:watchlistLink(row.public_id), entity:entityLink(row.entity_type,row.entity_value), map:mapLink(first?.lat,first?.lng), sources:[...new Set((snapshot.results||[]).map((r:any)=>r.provider).filter(Boolean))] }; }
